/*
 Quantcast measurement tag
 Copyright (c) 2008-2017, Quantcast Corp.
*/
window.__qc=function(b){if(b.__qc)return b.__qc;var q=b.document,x=b.navigator,M="4dcfa7079941 127fdf7967f31 588ab9292a3f 32f92b0727e5 22f9aa38dfd3 a4abfe8f3e04 18b66bc1325c 958e70ea2f28 bdbf0cb4bbb 65118a0d557 40a1d9db1864 18ae3d985046 3b26460f55d".split(" "),F=!1,E=0,d=[],g=[],k=[],v={tcYgbCswcTSeq:1,"01-0VIaSjnOLg":1,aD1qr93XuF6aC:1,"56WJ0KtIxWJ_2":1,T1nhLcmCjVzQS:1,zddNYNtUkUhdQ:1,"59TntzuqummDw":1,P7x87XHnVfbWr:1,HGAVM7nQJ_sep:1,"w9vzus-GKCA0U":1,"00TsOkvHvnsZU":1,effSsmMYCbAck:1,PFW5FesqXn206:1,
"0dYLvhSGGqUWo":1,c1rF4kxgLUzNc:1,"5brKQLtleyIQU":1,"mEzuYq24VEJ-3":1,"57OGVHgSOoedo":1,"e7wR0qsM6-pDa":1,"8tgFhCTDYhV2V":1,"82MbSinIaQJw2":1,buQ2dAnrdTGCS:1,"49SVsgIZlUqPk":1,eeFYJkotb1rUU:1,EzVU5HfAMVqEV:1,"45nh8QKbsf2Xk":1,sLJ2v5QaN4z2Y:1,"5cvC4NOeGmtNA":1,"573scDfDoUH6o":1,"915Y6SMHQQJHI":1,z0zMG4nCgXzzj:1,"124BfeS-bwiSE":1,"ZzStSGgW6hG-4":1,KUMT4fYgcdEeg:1,d9vfr8QTWnv1E:1,fug7wP0GuN1h6:1,cd12aNCzw_ZaB:1,"51zXP5Cc9sxvQ":1,"4dIM5nVs2rFio":1,"8fZNjMQsH1Ews":1,C6W3aFrWFMS7m:1,N7ekbgK3G3jrt:1,dfQGRefil9mes:1,
"9axVJDmh4EHIM":1,NPcfSf1E0V1T1:1,"72V4-XKpaKDrE":1,"8cV3w6ZJH0sXI":1,sHwqAaPHqVjee:1,b15U9CAASyBMc:1},l=[],r={},G=0,H=[],z=null,W={},w={},ia=null,t,X=[].slice,ja,Y,N,n,B,Z,O,ka,la,ma,I,$,P,Q,na,J,oa,pa,qa,ra,p,sa,D,R,ta,aa,ua,va,ba,s,wa,ca,S,T,xa,ya,U,za,da,ea,Aa,fa,A,K,L,V,ga,u=function(a){try{return{init:Q,hash:P,rules:xa,hasRules:U,defaults:Aa,__qc:function(){return!0}}[a].apply(null,X.call(arguments,1))}catch(c){return!1}};u.evts=0;u.v=2;u.SD=M;u.qpixelsent=[];T=function(a){var c=a?a.length||
0:0,e;for(e=0;e<c;e++)if(!a[e])return!1;return!0};ea=function(a){(a=a||b._qacct)&&(ba(l,a)||l.push(a))};ba=function(a,c){var e=a.length,b;for(b=0;b<e;b++)if(a[b]===c)return!0;return!1};ca=function(a){return{}.toString.call(a).match(/\s([a-zA-Z]+)/)[1].toLowerCase()};S=function(a){var c,e;c=ca(a);if("array"===c)return a.slice(0);if("object"===c){c={};for(e in a)a.hasOwnProperty(e)&&(c[e]=a[e]);return c}return"string"===c?""+a:a};U=function(a){return ba(k,a)};Aa=function(a,c){var e;a&&((e=W[a])&&(c=
V(c,e)),c.qacct&&delete c.qacct,W[a]=c)};fa=function(a){var c,e;if(n(a))for(c in a)if("string"==typeof a[c]){c=a.event||"load";e=a.media||"webpage";"rule"!==c&&"load"!==c||"webpage"!==e&&"ad"!==e?p(a):(e=a.qacct||b._qacct,a.qacct=e,c=(c=w[e])?V(c,a):a,w[e]=c);ea(a.qacct);break}else"object"==typeof a[c]&&null!=a[c]&&fa(a[c])};V=function(a,c){var e={};e.qacct=a.qacct||c.qacct;e.event="load"===a.event||"load"===c.event?"load":a.event&&c.event?a.event||c.event:null;e.media=null;e.media="webpage"===a.media||
"webpage"===c.media?"webpage":"ad"===a.media||"ad"===c.media?"ad":a.media||c.media;aa(e,a,c);aa(e,c,a);e.event||delete e.event;e.media||delete e.media;return e};aa=function(a,c,e){var b,C,y,d,g,k;for(b in c)c.hasOwnProperty(b)&&!a.hasOwnProperty(b)&&(C=c[b],y=e[b],d="",g=!!C&&"string"==typeof C,k=!!y&&"string"==typeof y,g&&(d=C),g&&k&&(d+=","),k&&(d+=y),a[b]=d)};A=function(){var a=[],c,e;if(!(0<G)){wa();for(c in w)w.hasOwnProperty(c)&&w[c]&&(e=w[c],a.push(e),delete w[c]);1==a.length&&p(a[0]);1<a.length&&
p(a)}};K=function(a){var c=[],e,b;for(e=0;e<a.length;e++)b=a[e],v.hasOwnProperty(b.substring(2))?r[b]=5:U(b)||c.push(b);if(0===c.length)A();else for(e=0;e<c.length;e++)b=c[e],k.push(b),ua(b)};va=function(){for(var a;H[0]&&("loaded"==H[0].readyState||"complete"==H[0].readyState);)a=H.shift(),a.onreadystatechange=null,z.parentNode.insertBefore(a,z),L()};ua=function(a){var c,b;c=("https:"===q.location.protocol?"https://":"http://")+"rules.quantcount.com/rules-"+a+".js";z=z||q.scripts[0];G++;b=q.createElement("script");
"async"in b?(b.src=c,b.async=!1,b.onload=function(){r[a]=0;L()},b.onerror=function(){r[a]=1;L()},z.parentNode.insertBefore(b,z)):b.readyState?(r[a]=2,H.push(b),b.onreadystatechange=va,b.src=c):(r[a]=4,L())};L=function(){G-=0<G?1:0;A()};xa=function(){var a=!0,c,b,f;if(arguments.length){f=function(c){a?fa(c):p(c,!0)};for(c=0;c<arguments.length;c++)b=X.call(arguments[c],0),b.splice(1,0,f),ya.apply(null,b);a=!1;F&&A()}};ya=function(a,c){var b=[],f=[],C=c||p,y,d,l,ha,m;if((y=X.call(arguments,2))&&y.length){d=
y[0]||T;l=y[1];ha=y[2];y=ha.length;for(m=0;m<y;m++)b.push(!1),f.push(null);b={p:a,f:b,r:d,c:ha,a:l,v:f};U(a)||k.push(a);g.push(b);za(b,C)}};za=function(a,c){var b=a?a.c?a.c.length:0:0,f;for(f=0;f<b;f++)(function(b){var e,f;try{e=a.c[b][0],f=a.c[b].slice(1),f.splice(0,0,function(e){a.f[b]=!0;a.v[b]=e;da(a,c)}),e.apply(null,f)}catch(d){a.f[b]=!0,a.v[b]=!1,da(a,c)}})(f)};da=function(a,c){var b=a.a,f=a.v,C=a.r||T,d,g,k,l,m,h;(d=T(a.f))&&(d=d&&C(f));if(d)for(f=0;f<b.length;f++)try{g=b[f][0];k=1<b[f].length?
b[f].slice(1):[];k=k.concat(a.v);l=g.apply(null,k);m={qacct:a.p,event:"rule"};for(h in l)l.hasOwnProperty(h)&&"qacct"!==h&&(m[h]=l[h]);c(m)}catch(v){}};ja=function(){return Y(0)!==Y(6)?1:0};Y=function(a){a=new Date(2E3,a,1,0,0,0,0);var c=a.toGMTString(),c=new Date(c.substring(0,c.lastIndexOf(" ")-1));return a-c};N=function(a){return a.replace(/\./g,"%2E").replace(/,/g,"%2C")};B="function"===typeof encodeURIComponent?encodeURIComponent:N;n=function(a){return"undefined"!=typeof a&&null!=a};Z=function(){return Math.round(2147483647*
Math.random())};O=function(a){var c="",b=q.cookie,f;if(!b)return c;f=b.indexOf(a+"\x3d");a=f+a.length+1;-1<f&&(c=b.indexOf(";",a),0>c&&(c=b.length),c=b.substring(a,c));return c};ka=function(){var a="",c=I(),b,f,d;if(1===E)return";fpan\x3du;fpa\x3d";b=P(c);for(f=0;f<M.length;f++)if(M[f]===b)return";fpan\x3du;fpa\x3d";b=new Date;f=O("__qca");if(0<f.length){try{d=+f.split("-")[2],338688E5<b-d&&(q.cookie=["__qca\x3d",f,"; expires\x3d",(new Date(d+338688E5)).toGMTString(),"; path\x3d/; domain\x3d",c].join(""))}catch(k){}a+=
";fpan\x3d0;fpa\x3d"+f}0===O("__qca").length&&(f="P0-"+Z()+"-"+b.getTime(),q.cookie=["__qca\x3d",f,"; expires\x3d",(new Date(b.getTime()+338688E5)).toGMTString(),"; path\x3d/; domain\x3d",c].join(""),f=O("__qca"),a=0<f.length?a+(";fpan\x3d1;fpa\x3d"+f):a+";fpan\x3du;fpa\x3d");return a};la=function(a){q.cookie=a+"\x3d; expires\x3dThu, 01 Jan 1970 00:00:01 GMT; path\x3d/; domain\x3d"+I()};I=function(){var a,b,e,f;a=q.domain;"www."===a.substring(0,4)&&(a=a.substring(4,a.length));b=a.split(".");f=b.length;
if(3>f)return a;e=b[f-1];return 3>e.length?a:a=b[f-2]+"."+e};$=function(a,b){var e;for(e=0;e<b.length;e++)a^=b.charCodeAt(e),a+=(a<<1)+(a<<4)+(a<<7)+(a<<8)+(a<<24);return a};P=function(a){var b;b=$(2166136261,a);a=$(3386659096,a);return Math.round(Math.abs(b*a)/65536).toString(16)};R=function(a,c,e){var f="",d=b._qacct,k=null,g="webpage",l="load",v={},m,h,d=c?c.qacct||b._qacct:b._qacct;m=w[d];c?m&&(c=V(c,m)):c=m;d&&delete w[d];if(null!=c)for(h in c)v[h]=!0,c.hasOwnProperty(h)&&"string"===typeof h&&
"string"===typeof c[h]&&("uid"===h||"uh"===h?(na()||(k=P(c[h])),delete c[h]):"qacct"!==h&&(0<c[h].length?f+=";"+h+a+"\x3d"+B(c[h]):v[h]=!1,"media"===h&&(g=c[h]),"event"===h&&(l=c[h])));if("string"!==typeof d){if(!n(b._qacct)||0===b._qacct.length)return"";d=b._qacct}if(d&&(m=W[d]))for(h in m)"string"===typeof h&&m.hasOwnProperty(h)&&!v[h]&&(f+=";"+h+a+"\x3d"+B(m[h]),"media"===h&&(g=m[h]),"event"===h&&(l=m[h]));v=r[d];n(v)||(v=3);f+=";rf"+a+"\x3d"+v;"string"===typeof k&&(c.uh=k,f+=";uh"+a+"\x3d"+B(k));
if("webpage"===g&&"load"===l){for(c=0;c<u.qpixelsent.length;c++)if(u.qpixelsent[c]===d&&!e)return"";u.qpixelsent.push(d)}"ad"===g&&(E=1);return";a"+a+"\x3d"+d+f};ta=function(){var a=q.getElementsByTagName("meta"),b="",e,f,d,k;for(e=0;e<a.length;e++){d=a[e];if(1E3<=b.length)return b;n(d)&&n(d.attributes)&&n(d.attributes.property)&&n(d.attributes.property.value)&&n(d.content)&&(f=d.attributes.property.value,d=d.content,3<f.length&&"og:"===f.substring(0,3)&&(0<b.length&&(b+=","),k=80<d.length?80:d.length,
b+=N(f.substring(3,f.length))+"."+N(d.substring(0,k))))}return B(b)};ma=function(a){return"object"===typeof a?["p","approved"===a.consent?"a":"d","asserted"===a.source?"e":"i"].join(""):""};na=function(){var a=!1;n(b.external)&&(a=b.external,a="function"===typeof a.InPrivateFilteringEnabled&&!0===a.InPrivateFilteringEnabled());return a||"1"==x.doNotTrack||"yes"===x.doNotTrack||"1"==x.msDoNotTrack};p=function(a,c){var e="function"===typeof encodeURIComponent?"n":"s",f=Z(),k="",g="",l="",v="",r="",
m="u",h="1",s=0,t=[],p,w,z,A;E=0;n(u.qpixelsent)||(u.qpixelsent=[]);if(n(a))for(p in a)if("string"==typeof a[p]){g=R("",a,c);break}else"object"==typeof a[p]&&null!=a[p]&&(++s,g+=R("."+s,a[p],c));else"string"===typeof _qacct&&(g=R("",null,c));0!==g.length&&(s=x.cookieEnabled?"1":"0","undefined"!=typeof x.javaEnabled&&(m=x.javaEnabled()?"1":"0"),n(b._qmeta)&&(l=";m\x3d"+B(b._qmeta),b._qmeta=null),self.screen&&(k=screen.width+"x"+screen.height+"x"+screen.colorDepth),w=new Date,z=ja(),A=ka(),b.location&&
b.location.href&&(v=B(b.location.href)),q&&q.referrer&&(r=B(q.referrer)),b.self===b.top&&(h="0"),p=ta(),t.push("/pixel;r\x3d"+f+g+A+";ns\x3d"+h+";ce\x3d"+s),t.push(";je\x3d"+m+";sr\x3d"+k+";enc\x3d"+e+";dst\x3d"+z+";et\x3d"+w.getTime()+";tzo\x3d"+w.getTimezoneOffset()+l+";ref\x3d"+r+";url\x3d"+v+";ogl\x3d"+p),d.push(t),D())};sa=function(a){var c=new Image;a=[b.location.protocol,"//pixel.",oa(t)?"quantserve.com":"quantcount.com",a[0],";cm\x3d",ma(t),a[1]].join("");c.alt="";c.src=a;c.onload=function(){c&&
"number"==typeof c.width&&3===c.width&&la("__qca")}};D=function(){if(t)for(;d.length;)sa(d.shift());else ra()};oa=function(a){return!0===a||1===a||1===a||n(a)&&"approved"===a.consent?!0:!1};ra=function(){if(!n(t)){if(b.top===b.self){if("object"===typeof PrivacyManagerAPI&&"function"===typeof PrivacyManagerAPI.callApi){pa("getConsent","advertising");return}}else if(b.postMessage&&"object"===typeof JSON){qa("getConsent","advertising");return}t=1}D()};pa=function(a,b){t=PrivacyManagerAPI.callApi(a,"quantserve.com",
I(),"truste.com",b);D()};qa=function(a,c){var e={PrivacyManagerAPI:{timestamp:(new Date).getTime(),action:a,self:"quantserve.com",domain:I(),authority:"truste.com",type:c}};if(b.addEventListener)b.addEventListener("message",J,!1);else if(b.attachEvent)b.attachEvent("onmessage",J);else{t=!0;D();return}try{b.top.postMessage(JSON.stringify(e),"*")}catch(d){}ia=setTimeout(function(){n(t)||(t=!0,D())},25)};J=function(a){var c=null;if(a.source===window.top){try{c="object"===typeof JSON&&JSON.parse(a.data)}catch(e){}c&&
"object"===typeof c.PrivacyManagerAPI&&(clearTimeout(ia),b.removeEventListener?window.removeEventListener("message",J,!1):b.detachEvent&&window.detachEvent("onmessage",J),t=c.PrivacyManagerAPI,D())}};ga=function(){var a=arguments,b,e;s([].slice.call(a));for(e=0;e<a.length;e++)b=a[e],p(b);l.length?K(l.slice(0)):A()};s=function(a){var c=ca(a);if("array"===c)for(c=0;c<a.length;c++)s(a[c]);else"object"===c&&ea(a.qacct||b._qacct)};wa=function(){var a;b._qevents.length||b.ezt.length||"undefined"===typeof _qacct||
p({qacct:b._qacct});if(!u.evts){for(a in b._qevents)b._qevents.hasOwnProperty(a)&&p(b._qevents[a]);for(a in b.ezt)b.ezt.hasOwnProperty(a)&&p(b.ezt[a]);b._qevents={push:ga};b.ezt.push=function(){var a=arguments,e;if(n(b.queueManager))for(e=0;e<a.length;e++)b.queueManager.push(a[e]);else ga.apply(this,arguments)};u.evts=1}};Q=function(){var a;n(b._qevents)||(b._qevents=[]);n(b.ezt)||(b.ezt=[]);b._qoptions&&(a=S(b._qoptions),s(b._qoptions),b._qevents.push(a),b._qoptions=null);b.qcdata&&(a=S(b.qcdata),
s(b.qcdata),b._qevents.push(a),b.qcdata=null);b.smarttagdata&&(a=S(b.smarttagdata),s(b.smarttagdata),b._qevents.push(a),b.smarttagdata=null);u.evts||(b._qevents.push=function(){s([].slice.call(arguments));K(l.slice(0));return[].push.apply(b._qevents,arguments)},b.ezt.push=function(){s([].slice.call(arguments));K(l.slice(0));return[].push.apply(b.ezt,arguments)});s(b.ezt);s(b._qevents);s({qacct:b._qacct});b._qoptions=null;l.length?K(l.slice(0)):A();F=!0};b.quantserve=b.quantserve||Q;u.quantserve=Q;
return u}(window);
try{__qc("hasRules","p-FusEMnpXn6KFm")||function(b,q,x){try{__qc("defaults",b,{labels:"_fp.event.Default"})}catch(M){}var F=function(b,d,g){return b?"nc"===b?!d||!g||0>d.indexOf(g):"eq"===b?d===g:"sw"===b?0===d.indexOf(g):"ew"===b?(b=d.length-g.length,d=d.lastIndexOf(g,b),-1!==d&&d===b):"c"===b?0<=d.indexOf(g):!1:!1},E=function(b){var d=x.createElement("a");d.href=b;return d},d=function(b,d,g){var r;r=q.top===q.self?x.location.pathname:E(x.referrer).pathname;F(d,r,g)?b(r):b(!1)},g=function(b){return"array"===
{}.toString.call(b).match(/\s([a-zA-Z]+)/)[1].toLowerCase()?{labels:b.join(",")}:{labels:""+b}};__qc("rules",[b,null,[[g,"_fp.event.Homepage"]],[[d,"eq","/"]]],[b,null,[[g,"_fp.event.JIRA"]],[[d,"eq","/software/jira"]]],[b,null,[[g,"_fp.event.JIRA Service Desk"]],[[d,"eq","/software/jira/service-desk"]]],[b,null,[[g,"_fp.event.Confluence"]],[[d,"eq","/software/confluence"]]],[b,null,[[g,"_fp.event.HIpChat"]],[[d,"eq","/software/hipchat"]]],[b,null,[[g,"_fp.event.Bitbucket"]],[[d,"eq","/software/bitbucket"]]],
[b,null,[[g,"_fp.event.Teams - Software"]],[[d,"eq","/teams/software"]]],[b,null,[[g,"_fp.event.Teams - Operations"]],[[d,"eq","/teams/operations"]]],[b,null,[[g,"_fp.event.Teams - IT"]],[[d,"eq","/teams/it"]]],[b,null,[[g,"_fp.event.Teams - HR"]],[[d,"eq","/teams/hr"]]],[b,null,[[g,"_fp.event.Teams - Marketing"]],[[d,"eq","/teams/marketing"]]],[b,null,[[g,"_fp.event.Teams - Legal"]],[[d,"eq","/teams/legal"]]],[b,null,[[g,"_fp.event.Teams - Finance"]],[[d,"eq","/teams/finance"]]],[b,null,[[g,"_fp.event.Try JIRA"]],
[[d,"eq","/software/jira/try"]]],[b,null,[[g,"_fp.event.Sign Up for Bitbucket"]],[[d,"eq","/account/signup/"]]],[b,null,[[g,"_fp.event.Try Confluence"]],[[d,"eq","/software/confluence/try"]]],[b,null,[[g,"_fp.event.Try JIRA Service Desk"]],[[d,"eq","/software/jira/service-desk/try"]]],[b,null,[[g,"_fp.event.Try JIRA Core"]],[[d,"eq","/software/jira/core/try"]]],[b,null,[[g,"_fp.event.Sign Up for HipChat"]],[[function(b,d,g){var r;r=q.top===q.self?x.location.href:E(x.referrer).href;F(d,r,g)?b(r):b(!1)},
"c","www.hipchat.com"],[d,"eq","/sign_up"]]],[b,null,[[g,"_fp.event.Download Bamboo"]],[[d,"eq","/software/bamboo/download"]]],[b,null,[[g,"_fp.event.Download Clover"]],[[d,"eq","/software/clover/download"]]],[b,null,[[g,"_fp.event.Download FishEye"]],[[d,"eq","/software/fisheye/download"]]],[b,null,[[g,"_fp.event.Download Crucible"]],[[d,"eq","/software/crucible/download"]]])}("p-FusEMnpXn6KFm",window,document)}catch(nfe$$4){}quantserve();
try{window.smarttagdata&&window._qevents.push(window.smarttagdata),window.qcdata&&window._qevents.push(window.qcdata)}catch(nfe$$5){};